#!/bin/sh
#
## Copyright (C) 1996-2023 The Squid Software Foundation and contributors
##
## Squid software is distributed under GPLv2+ license and includes
## contributions from numerous individuals and organizations.
## Please see the COPYING and CONTRIBUTORS files for details.
##

# test all header files (.h) for dependency issues.
#
# Ideally this test should be performed twice before any code is accepted.
# With or without inline enabled.  This is needed because the .cci files
#  are only included into the .h files when inline mode is enabled.
#
# This script should be run from the makefile with the directory path and ccflags
#
cc="${1}"
shift

exitCode=0

echo "1..$#"
testNum=1
exitCode=0
for f in $@; do
    t="testhdr_`basename ${f}`"
    if [ ! -f "$t.o" -o $f -nt "$t.o" ]; then
        echo >$t.cc <<EOF
/* This file is AUTOMATICALLY GENERATED. DO NOT ALTER IT */
#include "squid.h"
#include "${f}"
int main( int argc, char* argv[] ) { return 0; }
EOF
        if ${cc} -c -o $t.o $t.cc ; then
            echo "ok ${testNum} - ${f}"
        else
            echo "not ok ${testNum} - ${f}"
            exitCode=1
        fi
        rm $t.cc $t.o
        testNum=`expr ${testNum} + 1`
    fi
done

#who ever said that the test program needs to be meaningful?
exit $exitCode
