#!/usr/bin/awk -f
#
## Copyright (C) 1996-2021 The Squid Software Foundation and contributors
##
## Squid software is distributed under GPLv2+ license and includes
## contributions from numerous individuals and organizations.
## Please see the COPYING and CONTRIBUTORS files for details.
##

/HERE/ {
  # HERE is obsolete
  gsub(/,[ ]?HERE\)/, ", MYNAME)");
  gsub(/,[ ]?[ ]?HERE[ ]?[ ]?<<[ ]?["]:[ ]/, ", \"");
  gsub(/,[ ]?[ ]?HERE[ ]?[ ]?<<[ ]?/, ", ");
  gsub(/[ ][ ][ ][ ]HERE[ ]?[ ]?<<[ ]?/, "    ");
}
{ print }
