.TH squid_radius_auth 8 "7 August 2004" "Squid RADIUS Auth"
.
.SH NAME
squid_radius_auth - Squid RADIUS authentication helper
.
.SH SYNOPSIS
.B squid_radius_auth
-f configfile
.br
.B squid_radius_auth
-h "server" [-p port] [-i identifier] -w secret
.
.SH DESCRIPTION
This helper allows Squid to connect to a RADIUS server to
validate the user name and password of Basic HTTP authentication.
.
.TP
.BI "-f " "configfile "
Specifies the path to a configuration file. See the CONFIGURATION section
for details.
.
.TP
.BI "-h " server
Alternative method of specifying the server to connect to
.
.TP
.BI "-p " port
Specify another server port where the RADIUS server listens for requests
if different from the default RADIUS port.  Normally not specified.
.
.TP
.BI "-i " identifier
Unique identifier identifying this Squid proxy to the RADIUS server.
If not specified the IP address is used as to identify the proxy.
.TP
.BI "-w " secret
Alternative method of specifying the shared secret. Using the
configuration file is generally more secure and recommended.
.
.TP
.BI "-t " timeout
RADIUS request timeout. Default 10 seconds.
.
.SH CONFIGURATION
The configuration specifies how the helper connects to RADIUS.
The file contains a list of directives (one per line). Lines
beginning with a # is ignored.
.
.TP
.BI "server " radiusserver
specifies the name or address of the RADIUS server to connect to.
.
.TP
.BI "secret " somesecretstring
specifies the shared RADIUS secret.
.
.TP
.BI "identifier " nameofserver
specifies what the proxy should identify itsels as to the RADIUS server.
This directive is optional.
.
.TP
.BI "port " portnumber
Specifies the port number or service name where the helper should connect.
.SH AUTHOR
This manual page was written by 
.I Henrik Nordstrom <hno@squid-cache.org>
.P
squid_radius_auth is written by 
.I Marc van Selm <selm@cistron.nl>
with contributions from
.I Henrik Nordstrom <hno@squid-cache.org>
and many others
.
.SH QUESTIONS
Any questions on usage can be sent to 
.IR "Squid Users <squid-users@squid-cache.org>" ,
or to your favorite RADIUS list/friend if the question is more related to
RADIUS than Squid.
.
.SH REPORTING BUGS
Report bugs or bug-fixes to
.I Squid Bugs <squid-bugs@squid-cache.org>
or ideas for new improvements to 
.I Squid Developers <squid-dev@squid-cache.org>
.
.SH "SEE ALSO"
.BR RFC2058 " - Remote Authentication Dial In User Service (RADIUS)"
