.TH basic_radius_auth 8 "7 August 2004" "Squid RADIUS Auth"
.
.SH NAME
basic_radius_auth - Squid RADIUS authentication helper
.
.SH SYNOPSIS
.if !'po4a'hide' .B basic_radius_auth
.if !'po4a'hide' -f configfile
.br
.if !'po4a'hide' .B basic_radius_auth
.if !'po4a'hide' -h "server" [-p port] [-i identifier] -w secret
.
.SH DESCRIPTION
This helper allows Squid to connect to a RADIUS server to
validate the user name and password of Basic HTTP authentication.
.
.TP
.if !'po4a'hide' .BI "-f " "configfile "
Specifies the path to a configuration file. See the CONFIGURATION section
for details.
.
.TP
.if !'po4a'hide' .BI "-h " server
Alternative method of specifying the server to connect to
.
.TP
.if !'po4a'hide' .BI "-p " port
Specify another server port where the RADIUS server listens for requests
if different from the default RADIUS port.  Normally not specified.
.
.TP
.if !'po4a'hide' .BI "-i " identifier
Unique identifier identifying this Squid proxy to the RADIUS server.
If not specified the IP address is used as to identify the proxy.
.TP
.if !'po4a'hide' .BI "-w " secret
Alternative method of specifying the shared secret. Using the
configuration file is generally more secure and recommended.
.
.TP
.if !'po4a'hide' .BI "-t " timeout
RADIUS request timeout. Default 10 seconds.
.
.SH CONFIGURATION
The configuration specifies how the helper connects to RADIUS.
The file contains a list of directives (one per line). Lines
beginning with a # is ignored.
.
.TP
.if !'po4a'hide' .BI "server " radiusserver
specifies the name or address of the RADIUS server to connect to.
.
.TP
.if !'po4a'hide' .BI "secret " somesecretstring
specifies the shared RADIUS secret.
.
.TP
.if !'po4a'hide' .BI "identifier " nameofserver
specifies what the proxy should identify itself as to the RADIUS server.
This directive is optional.
.
.TP
.if !'po4a'hide' .BI "port " portnumber
Specifies the port number or service name where the helper should connect.
.SH AUTHOR
This program is written by 
.if !'po4a'hide' .I Marc van Selm <selm@cistron.nl>

With contributions from
.I Henrik Nordstrom <hno@squid-cache.org>
and many others.
.
This manual was written by 
.if !'po4a'hide' .I Henrik Nordstrom <hno@squid-cache.org>
.
.SH QUESTIONS
Questions on the usage of this program can be sent to the
.I Squid Users mailing list
.if !'po4a'hide' <squid-users@squid-cache.org>
or to your favorite RADIUS list/friend if the question is more related to
RADIUS than Squid.
.
.SH REPORTING BUGS
Report bugs or bug fixes using http://bugs.squid-cache.org/
.
Report serious security bugs to
.I Squid Bugs <squid-bugs@squid-cache.org>
.
Report ideas for new improvements to the
.I Squid Developers mailing list
.if !'po4a'hide' <squid-dev@squid-cache.org>
.
.SH "SEE ALSO"
.BR RFC2058 " - Remote Authentication Dial In User Service (RADIUS)"
