.if !'po4a'hide' .TH basic_pam_auth 8 "5 Sep 2003"
.
.SH NAME
basic_pam_auth \- PAM Basic authentication helper for Squid
.
.SH SYNOPSIS
.if !'po4a'hide' .B "basic_pam_auth [\-n \""
service name
.if !'po4a'hide' .B "\"] [\-t "
TTL
.if !'po4a'hide' .B "] [\-o] [\-1]"
.
.SH DESCRIPTION
.B basic_pam_auth
allows Squid to connect to a mostly any available PAM
database to validate the user name and password of Basic HTTP
authentication.
.
.SH OPTIONS
.if !'po4a'hide' .TP 12
.if !'po4a'hide' .B "\-s " "service\-name"
Specifies the PAM service name Squid uses, defaults to
.B squid
.
.if !'po4a'hide' .TP
.if !'po4a'hide' .B "\-t " TTL
Enables persistent PAM connections where the connection to the PAM
database is kept open and reused for new logins. The TTL specifies
how long the connection will be kept open (in seconds).  Default is
to not keep PAM connections open. Please note that the use of
persistent PAM connections is slightly outside the PAM
specification and may not work with all PAM configurations.
.
.if !'po4a'hide' .TP
.if !'po4a'hide' .B \-o
Do not perform the PAM account management group (account
expiration etc)
.
.SH CONFIGURATION
The program needs a PAM service to be configured in 
.BR /etc/pam.conf
or
.BR /etc/pam.d/squid
.PP
The default service name is
.B squid
, and the program makes use of the
.B auth
and
.B account
management groups to verify the password and the accounts validity.
.PP
For details on how to configure PAM services, see the PAM
documentation for your system. This manual does not cover PAM
configuration details.
.
.SH NOTES
.
When used for authenticating to local UNIX shadow password databases
the program must be running as root or else it won't have sufficient
permissions to access the user password database. Such use of this
program is not recommended, but if you absolutely need to then make
the program setuid root
.if !'po4a'hide' .RS
.if !'po4a'hide' .P
.if !'po4a'hide' .B chown root basic_pam_auth
.if !'po4a'hide' .br
.if !'po4a'hide' .B chmod u+s basic_pam_auth
.if !'po4a'hide' .RE
.PP
Please note that in such configurations it is also strongly recommended
that the program is moved into a directory where normal users cannot
access it, as this mode of operation will allow any local user to
brute-force other users passwords. Also note the program has not been
fully audited and the author cannot be held responsible for any security
issues due to such installations.
.
.SH AUTHOR
This program and documentation was written by
.if !'po4a'hide' .I Henrik Nordstrom <hno@squid-cache.org>
.
.SH COPYRIGHT
.PP
 * Copyright (C) 1996-2016 The Squid Software Foundation and contributors
 *
 * Squid software is distributed under GPLv2+ license and includes
 * contributions from numerous individuals and organizations.
 * Please see the COPYING and CONTRIBUTORS files for details.
.PP
Squid
.B basic_pam_auth
and this manual is Copyright 1999,2002,2003
.if !'po4a'hide' .I Henrik Nordstrom <hno@squid-cache.org>
.
Distributed under the GNU General Public License (GNU GPL) version 2 or later (GPLv2+).
.
.SH QUESTIONS
Questions on the usage of this program can be sent to the
.I Squid Users mailing list
.if !'po4a'hide' <squid-users@squid-cache.org>
.
.SH REPORTING BUGS
Bug reports need to be made in English.
See http://wiki.squid-cache.org/SquidFaq/BugReporting for details of what you need to include with your bug report.
.PP
Report bugs or bug fixes using http://bugs.squid-cache.org/
.PP
Report serious security bugs to
.I Squid Bugs <squid-bugs@squid-cache.org>
.PP
Report ideas for new improvements to the
.I Squid Developers mailing list
.if !'po4a'hide' <squid-dev@squid-cache.org>
.
.SH SEE ALSO
.if !'po4a'hide' .BR squid "(8), "
.if !'po4a'hide' .BR pam "(3), "
.if !'po4a'hide' .BR pam.conf "(5), "
.if !'po4a'hide' .BR chown "(1), "
.if !'po4a'hide' .BR chmod "(1), "
.if !'po4a'hide' .BR GPL "(7), "
.br
PAM Systems Administrator Guide
.br
The Squid FAQ wiki
.if !'po4a'hide' http://wiki.squid-cache.org/SquidFaq
.br
The Squid Configuration Manual
.if !'po4a'hide' http://www.squid-cache.org/Doc/config/

