.TH pam_auth 8 "5 Sep 2003" "Squid PAM Auth"
.
.SH NAME
pam_auth - Squid PAM authentication helper
.
.SH SYNOPSIS
squid_pam_auth [-n "service name"] [-t TTL] [-o] [-1]
.
.SH DESCRIPTION
This helper allows Squid to connect to a mostly any available PAM
database to validate the user name and password of Basic HTTP
authentication.
.
.TP
.BI "-s " "service-name"
Specifies the PAM service name Squid uses, defaults to "squid"
.
.TP
.BI "-t " TTL
Enables persistent PAM connections where the connection to the PAM
database is kept open and reused for new logins. The TTL specifies
how long the connection will be kept open (in seconds).  Default is
to not keep PAM connections open. Please note that the use of
persistent PAM connections is slightly outside the PAM
specification and may not work with all PAM configurations.
.
.TP
.BI "-o"
Do not perform the PAM account management group (account
expiration etc)

.
.SH CONFIGURATION
.
The program needs a PAM service to be configured in 
.B /etc/pam.conf
or
.B /etc/pam.d/<servicename>
.P
The default service name is "squid", and the program makes use
of the
.BR "" ' auth "' and '" account '
management groups to verify the password and the accounts validity.
.P
For details on how to configure PAM services, see the PAM
documentation for your system. This manual does not cover PAM
configuration details.
.
.SH NOTES
.
When used for authenticating to local UNIX shadow password databases
the program must be running as root or else it won't have sufficient
permissions to access the user password database. Such use of this
program is not recommended, but if you absolutely need to then make
the program setuid root
.RS
.P
.B chown root pam_auth
.br
.B chmod u+s pam_auth
.RE
.P
Please note that in such configurations it is also strongly recommended
that the program is moved into a directory where normal users cannot
access it, as this mode of operation will allow any local user to
brute-force other users passwords. Also note the program has not been
fully audited and the author cannot be held responsible for any security
issues due to such installations.
.
.SH AUTHOR
Squid pam_auth and this manual is written by
.I Henrik Nordstrom <hno@squid-cache.org>
.
.SH COPYRIGHT
Squid pam_auth and this manual is Copyright 1999,2002,2003
Henrik Nordstrom <hno@squid-cache.org>
.
.SH QUESTIONS
Questions on the usage of this program can be sent to the
.I Squid Users <squid-users@squid-cache.org>
mailing list.
.
.SH REPORTING BUGS
Report bugs or bug-fixes to
.I Squid Bugs <squid-bugs@squid-cache.org>
or ideas for new improvements to 
.I Squid Developers <squid-dev@squid-cache.org>
.
.SH "SEE ALSO"
.BR pam (8), " PAM Systems Administrator Guide"
