@echo off
echo /* automatically generated by %0
echo  * do not edit manually
echo  */
echo #define DEFAULT_CONFIG_FILE "%1"
echo #define DEFAULT_SQUID_ERROR_DIR "%2"
echo #define DEFAULT_CACHEMGR_CONFIG "%3"
echo /* Info of package */
FOR /F "tokens=1,2 delims== " %%a in (squid_version.mak) do echo #define %%a "%%b"
