@echo off
if exist %temp%\repl_modules.txt del %temp%\repl_modules.txt
:loop
echo %1 >> %temp%\repl_modules.txt
shift /1
if NOT "%1"=="" goto :loop
echo /* automatically generated by %0 %*
echo  * do not edit
echo  */
echo #include "squid.h"
echo #include "Store.h"
for /F %%m in (%temp%\repl_modules.txt) do echo extern REMOVALPOLICYCREATE createRemovalPolicy_%%m;
echo void storeReplSetup(void)
echo {
for /F %%m in (%temp%\repl_modules.txt) do echo 	storeReplAdd("%%m", createRemovalPolicy_%%m);
echo }
if exist %temp%\repl_modules.txt del %temp%\repl_modules.txt
