#!/bin/sh
# /bin/cp because GNU cp is installed sometimes and has different syntax
# This file has been changed for Squid 2

failed()
{
	# show failed message and exit
	echo "FAILED ($*)"
	exit 1
}

#	check if caller runs as super user:
[ `/usr/ucb/whoami` = root ] || failed "must be super user"

PRG=Squid
SRCDIR=`cd ../..;pwd`
REL=`basename $SRCDIR | sed 's/.*-//'`

# Make info file from info.in:
cat info.in | sed "s/--VERSION--/$REL/" | sed "s/--DATE--/`date`/" >info

TMPDIR=/tmp/${PRG}
# Cleanup previous package creation
rm -rf ${TMPDIR}
rm -rf ${PRG}.pkg

# Create pre- and post-install scripts for the package, make sure these
# are executable
for f in post_install pre_install
do
	/bin/cp -p ${f} ${PRG}.${f}
	chmod 755 ${PRG}.${f}
done
/bin/cp -p info ${PRG}.info
chmod 644 ${PRG}.info

mkdirs ${TMPDIR}/usr/local/squid/etc ${TMPDIR}/usr/local/squid/logs
/bin/cp -pr /usr/local/squid/bin ${TMPDIR}/usr/local/squid
/bin/cp -pr /usr/local/squid/etc/squid.conf.default ${TMPDIR}/usr/local/squid/etc
# SQUID 2 (comment out if Squid 1)
/bin/cp -pr /usr/local/squid/etc/mime.conf.default ${TMPDIR}/usr/local/squid/etc
/bin/cp -pr /usr/local/squid/etc/icons ${TMPDIR}/usr/local/squid/etc
/bin/cp -pr /usr/local/squid/etc/errors ${TMPDIR}/usr/local/squid/etc
# END SQUID 2
strip ${TMPDIR}/usr/local/squid/bin/*
# It turns out that the Run* scripts are sometimes not executable
chmod 755 ${TMPDIR}/usr/local/squid/bin/*
/etc/chown -R nobody.other ${TMPDIR}/usr/local/squid

/NextAdmin/Installer.app/package /tmp/${PRG} ${PRG}.info
/bin/cp ${PRG}.pre_install ${PRG}.pkg
/bin/cp ${PRG}.post_install ${PRG}.pkg
/bin/cp -p Squid.pkg.README ${PRG}-${REL}.README

# Cleanup:
for f in post_install pre_install info
do
	rm ${PRG}.${f}
done
rm info
