.SUFFIXES: .pkg .tar .info

PRG=Squid
TIMESTAMP=.pkg_made
PKGNAME=${PRG}.pkg
TARNAME=${PRG}-${VERSION}.${ARCHS}.tar.gz

${TIMESTAMP}: /usr/local/squid/sbin/squid Squid.pkg.README info.in post_install \
	pre_install makepkg Makefile.real
	./makepkg
	touch ${TIMESTAMP}

${TARNAME}: ${TIMESTAMP}
	gnutar zcvf ${TARNAME} ${PKGNAME} ${PRG}-${VERSION}.README

tar: ${TARNAME}

pkg: ${TIMESTAMP}

clean:
	rm -rf ${PKGNAME} ${TARNAME} ${PRG}-${VERSION}.README ${TIMESTAMP}

echo:
	echo ${PKGNAME}
