#!/bin/sh
echo "/* automatically generated by $0 $*"
echo " * do not edit"
echo " */"
echo "#include \"squid.h\""
echo ""
for module in "$@"; do
   echo "extern AUTHSSETUP authSchemeSetup_${module};"
done
echo "void authSchemeSetup(void)"
echo "{"
for module in "$@"; do
   echo "	authSchemeAdd(\"$module\", authSchemeSetup_${module});"
done
echo "}"
