#!/bin/sh
echo "/* automatically generated by $0 $*"
echo " * do not edit"
echo " */"
echo "#include \"squid.h\""
echo "#include \"Store.h\""
echo ""
for module in "$@"; do
   echo "extern REMOVALPOLICYCREATE createRemovalPolicy_${module};"
done
echo "void storeReplSetup(void)"
echo "{"
for module in "$@"; do
   echo "	storeReplAdd(\"$module\", createRemovalPolicy_${module});"
done
echo "}"
