/*
 * Copyright (C) 1996-2023 The Squid Software Foundation and contributors
 *
 * Squid software is distributed under GPLv2+ license and includes
 * contributions from numerous individuals and organizations.
 * Please see the COPYING and CONTRIBUTORS files for details.
 */

#ifndef SQUID_SRC_REPL_MODULES_H
#define SQUID_SRC_REPL_MODULES_H

/*
 * Note: repl_modules.cc will be autogenerated.
 */

void storeReplSetup(void);

#endif /* SQUID_SRC_REPL_MODULES_H */

