#!/bin/sh
#
# This external acl helper checks the Kerberos group information without
# continues ldap queries by leveraging the kerbors ticket group information
# i.e. PAC field
#
# It requires only during startup aldap query to get the SID for the group name.
#
# Squid config lines:
# auth_param negotiate program /opt/squid/sbin/negotiate_wrapper_auth -d --ntlm /usr/bin/ntlm_auth --helper-protocol=squid-2.5-ntlmssp --domain SAMBA.HOME --kerberos /opt/squid/sbin/negotiate_kerberos_auth -d -s GSS_C_NO_NAME -k /etc/squid/squid.keytab -t none
# external_acl_type test_acl ipv4 %LOGIN %note{group} /opt/squid/sbin/negotiate_external_acl
# acl squid_allow external test_acl
#
# Use KRB5_KTNAME and KRB5_CONFIG to change system krb5 settings
#
# GET SID for Group
#
# Please change sample values with real valuse
#
export PRINCIPAL="HTTP/squid.example.com"
export DC="dc1.example.com"
export KRB5CCNAME="/tmp/squid_krb5cc"
export GROUPNAME="SQUID_ALLOW"
export BASEDN="DC=example,DC=com"
export EXTERNAL_ACL_DEBUG=1
#
#  
#
MSG=$(kinit -k $PRINCIPAL 2>&1)
if test -n "$MSG" ; then
  (>&2 echo "`date +"%Y/%m/%d %H:%M:%S"`| negotiate_external_acl: ERROR: $MSG")
fi
SID=$(ldapsearch -LLL -Ygssapi -H ldap://$DC:389 -s sub -b "$BASEDN" "(CN=$GROUPNAME)" objectsid 2>&1 | awk '{ if ( $0 ~/^object/ ) print $2}')

(>&2 echo "`date +"%Y/%m/%d %H:%M:%S"`| negotiate_external_acl: INFO: Group=$GROUPNAME, SID=$SID")

#
# Read from STDIN as a series of lines into 'input'."
#
while read input
do
  user=$(echo $input | awk '{ sub(/user=/,""); print $1 }')
  groups=r$(echo $input | awk '{ sub(/group=/,""); print $2 }')
  if test $EXTERNAL_ACL_DEBUG -eq 1 ; then
    (>&2 echo "$(date +"%Y/%m/%d %H:%M:%S")| negotiate_external_acl: DEBUG: user=$user")
    (>&2 echo "$(date +"%Y/%m/%d %H:%M:%S")| negotiate_external_acl: DEBUG: groups=$groups")
  fi
  result="ERR"
  if test -n "$groups" ; then
    IFS=,
    for group in $groups; do
      if test "$group" = "$SID" ; then
        if test $EXTERNAL_ACL_DEBUG -eq 1 ; then
          (>&2 echo "$(date +"%Y/%m/%d %H:%M:%S")| negotiate_external_acl: DEBUG: matched group: $group")
        fi
        result="OK"
        break
      fi
    done
    IFS=
  fi
  echo $result
done
