#ifndef _SQUID__SRC_AUTH_AUTHACLSTATE_H
#define _SQUID__SRC_AUTH_AUTHACLSTATE_H

typedef enum {
    AUTH_ACL_CHALLENGE = -2,
    AUTH_ACL_HELPER = -1,
    AUTH_ACL_CANNOT_AUTHENTICATE = 0,
    AUTH_AUTHENTICATED = 1
} AuthAclState;

#endif
