name: Test build on MacOS

on:
  push:
    branches: [ "master", "github-macos" ]
  pull_request:
    branches: [ "master" ]

env:
  PKG_CONFIG_PATH: /opt/homebrew/opt/openldap/lib/pkgconfig

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install prerequisite packages
      run: |
        brew install \
          automake coreutils cppunit gawk \
          gnu-getopt gnu-sed grep \
          make
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Prepare build
      run: |
        export CFLAGS="-Wno-compound-token-split-by-macro ";
        ./bootstrap.sh && \
        mkdir btbuild && \
        cd btbuild && \
        ../configure --without-ldap
    - name: BuildIt!
      run: gmake -C btbuild -j $(nproc) all && gmake -C btbuild -j $(nproc) check
