name: Test build on MacOS

on:
  push:
    branches: [ "master", "auto", "github-macos" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install prerequisite packages
      run: |
        # brew update
        brew install \
          automake coreutils cppunit gawk \
          gnu-getopt gnu-sed grep \
          make openldap cyrus-sasl
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 5
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true
        max-size: "2G"
        key: "ccache-${{ runner.os }}-${{ runner.arch }}"
        append-timestamp: false
        # variant: sccache
    - name: Build
      run: |
        eval `brew shellenv`
        export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/openldap/lib/pkgconfig:$HOMEBREW_PREFIX/opt/cyrus-sasl/lib/pkgconfig"
        export GETOPT="$HOMEBREW_PREFIX/opt/gnu-getopt/bin/getopt"
        export MAKE="$HOMEBREW_PREFIX/bin/gmake"
        export pjobs="-j`nproc`"
        env
        ./test-builds.sh --aggressively-use-config-cache --cleanup --verbose layer-02-maximus
        # ./test-builds.sh --verbose --aggressively-use-config-cache
