name: Test build on MacOS

on:
  push:
    branches: [ "master", "auto", "github-macos" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      fail-fast: true
      matrix:
        layer:
          - layer-00-default
          - layer-01-minimal
          - layer-02-maximus
          - layer-04-noauth-everything

    steps:
    - name: Install prerequisite packages
      run: |
        # brew update
        brew install \
          automake coreutils cppunit gawk \
          gnu-getopt gnu-sed grep \
          make openldap cyrus-sasl
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 5
    # - name: Setup ccache
    #   uses: hendrikmuhs/ccache-action@v1.2
    #   with:
    #     create-symlink: true
    #     max-size: "333M"
    #     key: "ccache-${{ runner.os }}-${{ runner.arch }}"
    #     append-timestamp: true
    #     # variant: sccache
    - name: Build layer
      run: |
        eval `brew shellenv`
        export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/openldap/lib/pkgconfig:$HOMEBREW_PREFIX/opt/cyrus-sasl/lib/pkgconfig"
        export GETOPT="$HOMEBREW_PREFIX/opt/gnu-getopt/bin/getopt"
        export pjobs="-j`nproc`"
        export MAKE="$HOMEBREW_PREFIX/bin/gmake ${pjobs}"
        ./test-builds.sh --verbose --aggressively-use-config-cache --cleanup ${{ matrix.layer}}
