name: Test build on MacOS

on:
  push:
    branches: [ "master", "github-macos" ]
  pull_request:
    branches: [ "master" ]

jobs:    
  build:

    runs-on: macos-latest

    steps:
    - name: Install prerequisite packagesx
      run: |
        brew install \
          automake coreutils cppunit gawk \
          gnu-getopt gnu-sed grep \
          make
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Prepare build
      run: |
        ./bootstrap.sh &&
        mkdir btbuild &&
        cd btbuild &&
        export PKG_CONFIG_PATH="/opt/homebrew/opt/openldap/lib/pkgconfig" &&
        CFLAGS="-Wno-compound-token-split-by-macro " \
        CPPFLAGS="`pkg-config --cflags ldap`" \
        LDFLAGS="`pkg-config --libs ldap`" \
        ../configure
    - name: BuildIt!
      run: gmake -C btbuild -j $(nproc) all && gmake -C btbuild -j $(nproc) check
