name: Test build on MacOS

on:
  push:
    branches: [ "master", "github-macos" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install prerequisite packages
      run: |
        brew install \
          automake coreutils cppunit gawk \
          gnu-getopt gnu-sed grep \
          make openldap cyrus-sasl
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Prepare build
      run: |
        export PKG_CONFIG_PATH=PKG_CONFIG_PATH="`brew list openldap | grep ldap.pc | head -1 | xargs dirname`:`brew list cyrus-sasl | grep libsasl2.pc | head -1 | xargs dirname`";
        export CFLAGS="-Wno-compound-token-split-by-macro ";
        export CPPFLAGS="`pkg-config --cflags ldap libsasl2`";
        export LDFLAGS="`pkg-config --libs ldap libsasl2`";
        ./bootstrap.sh && \
        mkdir btbuild && \
        cd btbuild && \
        ../configure
    - name: Build It!
      run: gmake -C btbuild -j $(nproc) all && gmake -C btbuild -j $(nproc) check
    - name: Run it!
      run: ./btbuild/src/squid -k parse -f btbuild/src/squid.conf.default
