name: Test build on MacOS

on:
  push:
    branches: [ "master", "github-macos" ]
  pull_request:
    branches: [ "master" ]

env:
  PKG_CONFIG_PATH: /opt/homebrew/opt/openldap/lib/pkgconfig

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install prerequisite packages
      run: |
        brew install \
          automake coreutils cppunit gawk \
          gnu-getopt gnu-sed grep \
          make
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Prepare build
      run: |
        export PKG_CONFIG_PATH="/opt/homebrew/opt/openldap/lib/pkgconfig" ;
        printf "pkg-config --cflags ldap: %s" "`pkg-config --cflags ldap`" &&
        printf "pkg-config --libs ldap: %s" "`pkg-config --libs ldap`" &&
        export \
          CFLAGS="-Wno-compound-token-split-by-macro " \
          CPPFLAGS="`pkg-config --cflags ldap`" \
          LDFLAGS="`pkg-config --libs ldap`" ;\
        ./bootstrap.sh &&
        mkdir btbuild &&
        cd btbuild &&
        ../configure
    # - name: BuildIt!
    #   run: gmake -C btbuild -j $(nproc) all && gmake -C btbuild -j $(nproc) check
